# Use a lightweight Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the application code to the container
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 7000

# Command to run the app
CMD ["gunicorn", "--bind", "0.0.0.0:7000", "wsgi:app"]
